### ISSUE TITLE
Docker image?

### ISSUE THREAD

**Issue by ptsteadman** [aaw3/ytdl-server#1]
Hey, thanks for working on this!
Is there a public docker image available?
The readme includes 'aaw3/ytdl-server:latest' but this does not seem to be public.

**Comment by ptsteadman** [comment]
Never mind, I realized I'd need to update the Dockerfile to work with my caprover setup, so I just [forked the repo ](https://github.com/computer-lab/ytdl-server)and had caprover build the image from the repo.

**Comment by aaw3** [comment]
Yeah sorry for any confusion, the image aaw3/ytdl-server:latest must be built locally. I currently do not have any images posted to docker hub.
